TRAIN:
  ENABLE: True
  DATASET: kinetics400
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: ''
  K400_PATH_TO_DATA_DIR : '/mnt/newdisk/mnt/newdisk/dataset/action/k400/label/timesformer_v15/'
  K400_PATH_PREFIX : '/mnt/newdisk/mnt/newdisk/dataset/action/k400/video/v30/frame/train_256/'
  # K400_PATH_TO_DATA_DIR : '/mnt/dataset/k400/label/timesformer_v15_for/'
  # K400_PATH_PREFIX: '/mnt/dataset/k400/train_256/'
  NUM_FRAMES: 8
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
  PRETRAINED_MODEL: '/mnt/weight/k400/3_19_e18_k400_v15/checkpoint_epoch_00017.pyth'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 15]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 400
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics400
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
  CHECKPOINT_FOLDER: ''
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
kmeans_dir: ''
OUTPUT_DIR: '/mnt/newdisk/mnt/newdisk/result/ucf101/k400/'
