TRAIN:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  NUM_SPATIAL_CROPS: 1
DATA:
  SSv2_PATH_TO_DATA_DIR: "/mnt/dataset/ssv2/v15/v15/"
  SSv2_PATH_PREFIX: "/mnt/dataset/ssv2/ssv2_frame_v30_for/"
  NUM_FRAMES: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: True
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
  PRETRAINED_MODEL: '/mnt/weight/ssv2/4_7_v15_k400/checkpoint_epoch_00005.pyth'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 7, 10]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 10  #15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 174
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
kmeans_dir : '/mnt/weight/kmeans/ssv2_v15_sharp_kmeans.pth'
OUTPUT_DIR: '/mnt/result/kec/ssv2_v15/5_22_new_Ek/'
