TRAIN:
  ENABLE: True
  DATASET: ucf101
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
  NUM_SPATIAL_CROPS: 1
DATA:
  PATH_TO_DATA_DIR: ""
  PATH_PREFIX: ""
  Ucf101_PATH_TO_DATA_DIR: "/mnt/newdisk/mnt/newdisk/dataset/DGC/DCCL/UCF101/v100/label/v100/"
  Ucf101_PATH_PREFIX: "/mnt/newdisk/mnt/newdisk/dataset/DGC/DCCL/UCF101/v100/UCF101_rgb/"
  NUM_FRAMES: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: True
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
  # PRETRAINED_MODEL: '/mnt/weight/ucf101/3_21_ucf101_for_e5/checkpoint_epoch_00005.pyth'
  # PRETRAINED_MODEL: '/mnt/weight/ucf101/1_14_ucf101_e8/checkpoint_epoch_00005.pyth'
  PRETRAINED_MODEL: '/mnt/newdisk/mnt/newdisk/result/action/timesformer/1_14_ucf101_e8/checkpoints/checkpoint_epoch_00005.pyth'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 15]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15  #15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 101
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: ucf101
  BATCH_SIZE: 64
  CHECKPOINT_FILE_PATH: ''
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
  CHECKPOINT_FILE_PATH : ''
  CHECKPOINT_FOLDER: ''
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
# OUTPUT_DIR: '/root/autodl-tmp/result/Simc-dec/ucf101/'
# OUTPUT_DIR: '/mnt/result/Simc_dec/ucf101/'
kmeans_dir: /mnt/newdisk/mnt/newdisk/result/ucf101/init/ucf101_3_28_2gpus/kmeans/
OUTPUT_DIR: /mnt/newdisk/mnt/newdisk/result/ucf101/init/ucf101_3_28_2gpus/
even_odd: False
